In [22]:
import networkx as nx
import numpy as np

In [2]:
G = nx.karate_club_graph()

In [9]:
A = nx.adjacency_matrix(G)

In [8]:
d_graph = dict()
FIRST_TRAVEL_KEY = 'first_travel'

In [24]:
np.sum(A[0, :])

16

In [28]:
d_graph = {node: {FIRST_TRAVEL_KEY: A[node, :].toarray()[0] / np.sum(A[node, :])} for node in G.nodes()}

In [29]:
d_graph[0][FIRST_TRAVEL_KEY]

array([0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.    , 0.    ,
       0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0625,
       0.    , 0.    ])

In [68]:
curn = 2
source = 0
p = 2
(A[curn, :] + ((1/p)-1)*(A[curn, :].multiply(A[source, :]))).toarray()

array([[1. , 0.5, 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 1. , 0. , 0. , 0. ,
        0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 1. , 1. , 0. , 0. , 0. , 1. , 0. ]])

In [69]:
PROBABILITIES_KEY = 'probs'
{current_node: {PROBABILITIES_KEY: {source: (A[curn, :] + ((1/p)-1)*(A[curn, :].multiply(A[source, :]))).toarray() for source in G.neighbors(current_node)}} for current_node in G.nodes()}

{0: {'probs': {1: array([[0.5, 1. , 0. , 0.5, 0. , 0. , 0. , 0.5, 1. , 1. , 0. , 0. , 0. ,
           0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
           0. , 1. , 1. , 0. , 0. , 0. , 1. , 0. ]]),
   2: array([[0.5, 0.5, 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0.5, 0. , 0. , 0. ,
           0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
           0. , 0.5, 0.5, 0. , 0. , 0. , 0.5, 0. ]]),
   3: array([[0.5, 0.5, 0. , 1. , 0. , 0. , 0. , 0.5, 1. , 1. , 0. , 0. , 0. ,
           0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
           0. , 1. , 1. , 0. , 0. , 0. , 1. , 0. ]]),
   4: array([[0.5, 1. , 0. , 1. , 0. , 0. , 0. , 1. , 1. , 1. , 0. , 0. , 0. ,
           1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
           0. , 1. , 1. , 0. , 0. , 0. , 1. , 0. ]]),
   5: array([[0.5, 1. , 0. , 1. , 0. , 0. , 0. , 1. , 1. , 1. , 0. , 0. , 0. ,
           1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.

In [41]:
A[curn, :].toarray()

array([[1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0]])

In [42]:
A[source, :].toarray()

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])